# Generated by Django 4.0.6 on 2022-07-06 22:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cpf', models.CharField(max_length=11)),
                ('saldo', models.FloatField()),
                ('conta', models.CharField(max_length=10)),
                ('telefone', models.CharField(max_length=11)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Cliente',
            },
        ),
        migrations.CreateModel(
            name='StatusTransacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=15)),
                ('descricao', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Status Transacao',
            },
        ),
        migrations.CreateModel(
            name='TipoTransacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=15)),
                ('descricao', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Tipo Transacao',
            },
        ),
        migrations.CreateModel(
            name='Transacoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.FloatField()),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_ultima_mudanca', models.DateTimeField(auto_now_add=True)),
                ('cliente_envio_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cliente_envio_id', to='conta_digital.cliente')),
                ('cliente_recebedor_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cliente_recebedor_id', to='conta_digital.cliente')),
                ('status_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conta_digital.statustransacao')),
                ('tipo_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conta_digital.tipotransacao')),
            ],
            options={
                'verbose_name_plural': 'Transacoes',
            },
        ),
        migrations.CreateModel(
            name='ClienteEnderecos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eh_principal', models.CharField(choices=[('sim', 'sim'), ('nao', 'nao')], default='sim', max_length=3)),
                ('cep', models.CharField(max_length=8)),
                ('rua', models.CharField(max_length=30)),
                ('numero', models.CharField(max_length=10)),
                ('bairro', models.CharField(max_length=20)),
                ('complemento', models.CharField(max_length=50)),
                ('cidade', models.CharField(max_length=20)),
                ('estado', models.CharField(max_length=20)),
                ('pais', models.CharField(max_length=20)),
                ('cliente_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conta_digital.cliente')),
            ],
            options={
                'verbose_name_plural': 'Cliente Enderecos',
            },
        ),
    ]
