# Generated by Django 4.0.6 on 2022-07-07 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conta_digital', '0002_alter_transacoes_status_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transacoes',
            name='status_id',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='conta_digital.statustransacao'),
        ),
    ]
