# Generated by Django 4.0.6 on 2022-07-11 22:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('banco_digital', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conta',
            name='conta',
            field=models.CharField(blank=True, editable=False, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='transacao',
            name='conta_cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conta_id', to='banco_digital.conta'),
        ),
        migrations.AlterField(
            model_name='transacao',
            name='conta_implicada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conta_implicada', to='banco_digital.conta'),
        ),
        migrations.AlterField(
            model_name='transacao',
            name='status_id',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='banco_digital.statustransacao'),
        ),
        migrations.AlterField(
            model_name='transacao',
            name='tipo_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='banco_digital.tipotransacao'),
        ),
    ]
