# Generated by Django 4.0.6 on 2022-07-08 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banco_digital', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conta',
            fields=[
                ('conta', models.UUIDField(primary_key=True, serialize=False)),
                ('saldo', models.FloatField()),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField()),
            ],
            options={
                'verbose_name_plural': 'Contas',
            },
        ),
    ]
