# Generated by Django 4.0.6 on 2022-07-14 00:36

from django.db import migrations, models
import localflavor.br.models


class Migration(migrations.Migration):

    dependencies = [
        ('banco_digital', '0002_alter_statustransacao_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='cnpj',
            field=localflavor.br.models.BRCNPJField(blank=True, max_length=18, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cpf',
            field=localflavor.br.models.BRCPFField(blank=True, max_length=14, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='tipo',
            field=models.CharField(choices=[('PF', 'PF'), ('PJ', 'PJ')], max_length=2),
        ),
    ]
