# Generated by Django 4.0.6 on 2022-07-17 04:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("banco_digital", "0005_alter_cliente_cnpj_alter_cliente_cpf_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="transacao",
            name="saldo_pre_operacao",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
